// "use client";

import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import { Metadata } from "next";



export const metadata: Metadata = {
  title: "Book Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      {/* <SessionProvider> */}
          {children}
        {/* </SessionProvider> */}
        </body>
    </html>
  );
}
